repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: 4380fbb73a154b5f5624794c1c78d9719ccc860f  # frozen: v2.16.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/biomejs/pre-commit
  rev: 5bb716344fd6979d991634e7ece88f407e599ee0  # frozen: v2.5.4
  hooks:
  - id: biome-check
